name: CI

on:
  push:
    branches: master
    tags-ignore: 
      - Release*
      - Deploy*
  pull_request:
    branches: '*'

jobs:
  build:
    name: Build
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest]
        sourcemod-version: [1.10-dev]
        include:
          - os: ubuntu-latest
            target-archs: x86

          - os: windows-latest
            target-archs: x86

    steps:
      - name: Install Linux packages
        if: runner.os == 'Linux'
        run: |
          sudo apt update
          sudo apt install -yq --no-install-recommends g++-multilib

      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: recursive
      
      - name: Checkout MetaMod
        uses: actions/checkout@v2
        with:
            repository: alliedmodders/metamod-source
            path: metamod-source
            submodules: recursive

      - name: Checkout SourceMod
        uses: actions/checkout@v2
        with:
          repository: alliedmodders/sourcemod
          ref: ${{ matrix.sourcemod-version }}
          path: sourcemod
          submodules: recursive


      - name: Build
        run: |
            mkdir build; cd build;
            cmake -DUSE_SDK=OFF -DTARGET_ARCH=x86 -DBUILD_TESTING=OFF -DCMAKE_BUILD_TYPE=Release ../
            cmake --build . --config Release -j 8
            
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: Build
          path: |
            **/*.ext.dll
            **/*.ext.so
